version: "3.8"
services:
    db:
        image: postgres:14.1-alpine
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
    mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"
    redis:
      image: redis:6.2-alpine
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning
volumes:
    db:
        driver: local
